---
title: "Geary_BDC21"
author: "Stephen Geary"
date: "3/4/2021"
output: html_document
---

```{r setup}

library(tidyverse)
library(retistruct) # contains line-line interaction function used in RR identifying function
library(LearnGeom) # calculates angles out of sets of coordinates
library(tidymodels)
library(vip)
library(ggpubr)
library(ggplot2)
library(car)

w_data_raw <- read.csv(
  "https://raw.githubusercontent.com/bigdatacup/Big-Data-Cup-2021/main/hackathon_womens.csv"
)
  
m_data_raw <- read.csv(
  "https://raw.githubusercontent.com/bigdatacup/Big-Data-Cup-2021/main/hackathon_scouting.csv"
)
  
all_data_raw <- rbind(w_data_raw, m_data_raw) 


```


```{r Organizing Data - Step 1}

ot_data_organized <- all_data_raw %>% 
  filter(Detail.4 == "t" | lead(Detail.4 == "t")) %>% 
  group_by(game_date, Home.Team, Away.Team) %>% 
  mutate(IsGoal = case_when(Event == "Goal" ~ T,
                            Event == "Shot" ~ F),
         Detail.2 = na_if(Detail.2, ""),
         Detail.3 = na_if(Detail.3, ""),
         Detail.4 = na_if(Detail.4, ""),
         Detail.1 = na_if(na_if(na_if(Detail.1, "Direct"), "Indirect"), "Played")) %>% 
  fill(Detail.1 ,Detail.2, Detail.3, Detail.4, IsGoal, .direction = "up") %>% 
  ungroup() %>% 
  rename(ShotType = Detail.1,
         ShotResult = Detail.2,
         Traffic = Detail.3,
         OneTimer = Detail.4,
         Passer = Player,
         Shooter = Player.2) %>% 
  drop_na() 

```


```{r Organizing Data - Creating function to identify RRPs}

crossesRR <- function(x1, y1, x2, y2){
  
  rr1 <- line.line.intersection(c(x1,y1), c(x2,y2), c(142,39.5), c(189,39.5), interior.only = T)
  rr2 <- line.line.intersection(c(x1,y1), c(x2,y2), c(142,45.5), c(189,45.5), interior.only = T)
  
  rr <- case_when(rr1[1] %in% c(Inf,NA) ~ FALSE,
                  rr2[1] %in% c(Inf,NA) ~ FALSE,
                  TRUE ~ TRUE)
  
  return(rr)
}

```


```{r Organizing Data - Creating modeling variables}


ot_data_comp <- ot_data_organized %>% 
  mutate(ShotDistance = ((189 - X.Coordinate.2)^2+(42.5 - Y.Coordinate.2)^2)^.5,
         PassDistance = ((X.Coordinate - X.Coordinate.2)^2+(Y.Coordinate - Y.Coordinate.2)^2)^.5) %>% 
  rowwise() %>% 
  mutate(PassShotAngleDiff = Angle(A = c(X.Coordinate, Y.Coordinate),
                               B = c(189, 42.5), 
                               C = c(X.Coordinate.2, Y.Coordinate.2)),
         ShotAngle = Angle(A = c(189, 39.5),
                           B = c(X.Coordinate.2, Y.Coordinate.2), 
                           C = c(189, 45.5)),
         RR = crossesRR(x1 = X.Coordinate,
                        y1 = Y.Coordinate,
                        x2 = X.Coordinate.2,
                        y2 = Y.Coordinate.2)
         )

```


```{r xG Model - Finalizing data & splitting }

ot_model_data <- ot_data_comp %>% 
  select(ShotDistance, PassDistance, ShotAngle, PassShotAngleDiff, RR, IsGoal)
  

set.seed(17)
ot_split <- initial_split(ot_model_data, strata = IsGoal)
ot_train <- training(ot_split)
ot_test <- testing(ot_split)

set.seed(1717)
ot_folds <- vfold_cv(ot_train, strata = IsGoal)

```


```{r xG Model - xgboost}

ot_train$IsGoal <- as.factor(ot_train$IsGoal)
ot_test$IsGoal <- as.factor(ot_test$IsGoal)
ot_split[["data"]][["IsGoal"]] <- as.factor(ot_split[["data"]][["IsGoal"]])

ot_train$RR <- as.factor(ot_train$RR)
ot_test$RR <- as.factor(ot_test$RR)
ot_split[["data"]][["RR"]] <- as.factor(ot_split[["data"]][["RR"]])

xgboost_spec <- boost_tree(trees = 1000, 
                            tree_depth = tune(), min_n = tune(), 
                            loss_reduction = tune(),
                            sample_size = tune(), mtry = tune(),
                            learn_rate = tune()) %>%
  set_engine("xgboost") %>%
  set_mode("classification") 


xgb_grid <- grid_latin_hypercube(
  tree_depth(),
  min_n(),
  loss_reduction(),
  sample_size = sample_prop(),
  finalize(mtry(), ot_train),
  learn_rate(),
  size = 30
)

xgb_wf <- workflow() %>%
  add_formula(IsGoal ~ .) %>%
  add_model(xgboost_spec)


set.seed(1717)
cv.folds <- vfold_cv(ot_train, strata = IsGoal)

doParallel::registerDoParallel()

set.seed(1717171717)

xgb_res <- tune_grid(
  xgb_wf,
  resamples = cv.folds,
  grid = xgb_grid,
  control = control_grid(save_pred = TRUE)
)

# show_best(xgb_res, "roc_auc")

best_params <- select_best(xgb_res, "roc_auc")

final_xgb <- finalize_workflow(xgb_wf, best_params)

final_res <- last_fit(final_xgb, ot_split)

### See how the model did

collect_metrics(final_res)


```


```{r Model - Modelling against whole dataset}

applied_xG <- cbind(ot_model_data, predict(final_xgb %>% fit(ot_train), 
                                           new_data = ot_model_data %>% mutate(RR = as.factor(RR)),
                                           type = "prob")) %>% 
                                  rename(xG = .pred_TRUE)


df_analysis <- left_join(x = applied_xG, y = ot_data_comp, copy = FALSE) %>% 
                     select(X.Coordinate, Y.Coordinate, X.Coordinate.2, Y.Coordinate.2,
                            ShotDistance, PassDistance, ShotAngle, PassShotAngleDiff, 
                            RR, IsGoal, xG) %>% 
                     arrange(-xG)


```


```{r Analysis - Variable importance}

library(vip)

plotvip <- final_xgb %>%
  fit(data = ot_split$data) %>%
  pull_workflow_fit() %>%
  vip(geom = "point") +
  theme_minimal()

plotvip


```






```{r Viz - Creating rink visualization (thank you for creating this Prashanth)}

viz_draw_rink <- function() {

  xseq <- seq(-4, 4, length = 100)
  theta1 <- seq(0, 2 * pi, length = 300)
  theta <- seq(0, 2 * pi, length = 300)
  dd <- (5 + 7 / 12) / 2

  ## Blank NHL Rink

  rink <-  ggplot2::ggplot(data = data.frame(x = 1, y = 1), aes(x, y)) +

    ggplot2::geom_path(data = data.frame(
      x = c(15, 87 + 13 * sin(seq(0, pi / 2, length = 20)),
            87 + 13 * sin(seq(pi / 2, 0, length = 20)), 15),
      y = c(-42.5, -42.5 + 15 - 15 * cos(seq(0, pi / 2, length = 20)),
            42.5 - 15 + 15 * cos(seq(pi / 2, 0, length = 20)), 42.5))) +
    ggplot2::geom_path(data = data.frame(
      x = c(15, -87 - 13 * sin(seq(0, pi / 2, length = 20)),
            -87 - 13 * sin(seq(pi / 2, 0, length = 20)), 15),
      y = c(-42.5, -42.5 + 15 - 15 * cos(seq(0, pi / 2, length = 20)),
            42.5 - 15 + 15 * cos(seq(pi / 2, 0, length = 20)), 42.5))) +
    ## Goal Lines
    ggplot2::geom_path(data = data.frame(x = c(89),
                                y = c(42.5 - 15 + sqrt(15^2 - (15 - 11)^2),
                                      -(42.5 - 15 + sqrt(15^2 - (15 - 11)^2)))),
              color = "#FFCCD8") +
    ggplot2::geom_path(data = data.frame(x = c(-89),
                                y = c(42.5 - 15 + sqrt(15^2 - (15 - 11)^2),
                                      -(42.5 - 15 + sqrt(15^2 - (15 - 11)^2)))),
              color = "#FFCCD8") +
    ## Nets
    ggplot2::geom_path(data = data.frame(x = c(90, 92, 92, 90)), y = c(-3, -3, 3, 3)) +
    ggplot2::geom_path(data = data.frame(x = c(-90, -92, -92, -90), y = c(-3,-3, 3, 3))) +

    ## Restricted Area
    ggplot2::geom_segment(aes(x = 89, y = -11, xend = 100, yend = -14), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(x = 89, y = 11, xend = 100, yend = 14), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(x = -89, y = -11, xend = -100, yend = -14), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(x = -89, y = 11, xend =-100, yend = 14), color = "#FFCCD8") +

    ## Red Line (Center Ice)
    ggplot2::geom_segment(aes(x = 0, y = -42.5, xend = 0, yend = 42.5), color = "#FFCCD8", size = 1) +

    ## Blue Lines
    ggplot2::geom_segment(aes(x = 25, y = -42.5, xend = 25,  yend = 42.5), color = "#CCE1FF", size = 1) +
    ggplot2::geom_segment(aes(x = -25, y = -42.5, xend = -25,  yend = 42.5), color = "#CCE1FF", size = 1) +

    ## Crease
    ggplot2::geom_polygon(data = data.frame(x = 1 * c(89, 83+xseq^2 / 4^2 * 1.5, 89),
                                   y = c(-4, xseq, 4)),
                 color = "#FFCCD8", fill = "#CCF5FF") +
    ggplot2::geom_polygon(data = data.frame(x = -1 * c(89, 83 + xseq^2 / 4^2 * 1.5, 89),
                                   y = c(-4, xseq, 4)),
                 color = "#FFCCD8", fill = "#CCF5FF") +

    ## Center Ice Circle
    ggplot2::geom_path(data = data.frame(x = 15 * sin(theta1)),
              y = 15 * cos(theta1), color = "#CCF5FF") +

    ## Faceoff Dots
    ggplot2::geom_polygon(data = data.frame(y = 22 + 1 * cos(theta),
                                   x = 20 + 1 * sin(theta)),
                 color = "#FFCCD8", fill = "#FFCCD8") +
    ggplot2::geom_polygon(data = data.frame(y = 22 + 1 * cos(theta),
                                   x = -20 + 1 * sin(theta)),
                 color = "#FFCCD8", fill = "#FFCCD8") +
    ggplot2::geom_polygon(data = data.frame(y = -22 + 1 * cos(theta),
                                   x = -20 + 1 * sin(theta)),
                 color = "#FFCCD8", fill = "#FFCCD8") +
    ggplot2::geom_polygon(data = data.frame(y = -22 + 1 * cos(theta),
                                   x = 20 + 1 * sin(theta)),
                 color = "#FFCCD8", fill = "#FFCCD8") +
    ggplot2::geom_polygon(data = data.frame(y = 22 + 1 * cos(theta),
                                   x = -69 + 1 * sin(theta)),
                 color = "#FFCCD8", fill = "#FFCCD8") +
    ggplot2::geom_polygon(data = data.frame(y = 22 + 1 * cos(theta),
                                   x = 69 + 1 * sin(theta)),
                 color = "#FFCCD8", fill = "#FFCCD8") +
    ggplot2::geom_polygon(data = data.frame(y = -22 + 1 * cos(theta),
                                   x = -69 + 1 * sin(theta)),
                 color = "#FFCCD8", fill = "#FFCCD8") +
    ggplot2::geom_polygon(data = data.frame(y = -22 + 1 * cos(theta),
                                   x = 69 + 1 * sin(theta)),
                 color = "#FFCCD8", fill = "#FFCCD8") +

    ## Faceoff Circles
    ggplot2::geom_segment(aes(y = 22 - 0.75, x = 69 - 2,
                     yend = 22 - 0.75, xend = 69 - 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 0.75, x = 69 - 2,
                     yend = 22 + 0.75, xend = 69 - 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 0.75, x = 69 + 2,
                     yend = 22 + 0.75, xend = 69 + 6), color= "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 0.75, x = 69 - 2,
                     yend = 22 - 0.75, xend = 69 - 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 0.75, x = 69 - 2,
                     yend = -22 + 0.75, xend = 69 - 6), color= "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 0.75, x = 69 + 2,
                     yend = -22 + 0.75, xend = 69 + 6), color= "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 0.75, x = 69 - 2,
                     yend = -22 - 0.75, xend = 69 - 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 0.75, x = 69 + 2,
                     yend = -22 - 0.75, xend = 69 + 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 0.75, x = 69 + 2,
                     yend = 22 - 0.75, xend = 69 + 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 0.75, x = -69 - 2,
                     yend = 22 + 0.75, xend = -69 - 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 0.75, x = -69 - 2,
                     yend = 22 - 0.75, xend = -69 - 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 0.75, x = -69 + 2,
                     yend = 22 + 0.75, xend = -69 + 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 0.75, x = -69 - 2,
                     yend = -22 + 0.75, xend = -69 - 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 0.75, x = -69 + 2,
                     yend = 22 - 0.75, xend = -69 + 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 0.75, x = -69 + 2,
                     yend = -22 + 0.75, xend = -69 + 6), color= "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 0.75, x = -69 - 2,
                     yend = -22 - 0.75, xend = -69 - 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 0.75, x = -69 + 2,
                     yend = -22 - 0.75, xend = -69 + 6), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 15, x = 69 - dd,
                     yend = 22 - 17, xend = 69 - dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 15, x = 69 + dd,
                     yend = 22 - 17, xend = 69 + dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 15, x = 69 + dd,
                     yend = 22+17, xend = 69 + dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 15, x = 69 - dd,
                     yend = 22 + 17, xend = 69 - dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 15, x = 69 - dd,
                     yend = -22 + 17, xend = 69 - dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 15, x = 69 + dd,
                     yend = -22 + 17, xend = 69 + dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 15, x = 69 - dd,
                     yend = -22 - 17, xend = 69 - dd), color= "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 15, x = 69 + dd,
                     yend = -22 - 17, xend = 69 + dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 15, x = -69 + dd,
                     yend = -22 + 17, xend = -69 + dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 15, x = -69 - dd,
                     yend = -22 - 17, xend = -69 - dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 15, x = -69 + dd,
                     yend = -22 - 17, xend = -69 + dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 15, x = -69 - dd,
                     yend = -22 + 17, xend = -69 - dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 15, x = -69 + dd,
                     yend = 22 - 17, xend = -69 + dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 15, x = -69 - dd,
                     yend = 22 - 17, xend = -69 - dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 15, x = -69 - dd,
                     yend = 22 + 17, xend = -69 - dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 15, x = -69 + dd,
                     yend = 22 + 17, xend = -69 + dd), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 0.75, x = 69 + 2,
                     yend = 22 + 3.75, xend = 69 + 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 0.75, x = 69 - 2,
                     yend = 22 + 3.75, xend = 69 - 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 0.75, x = 69 + 2,
                     yend = 22 - 3.75, xend = 69 + 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 0.75, x = 69 - 2,
                     yend = 22 - 3.75, xend = 69 - 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 0.75, x = -69 + 2,
                     yend = 22 + 3.75, xend = -69 + 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 + 0.75, x = -69 - 2,
                     yend = 22 + 3.75, xend = -69 - 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 0.75, x = -69 + 2,
                     yend = 22 - 3.75, xend = -69 + 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = 22 - 0.75, x = -69 - 2,
                     yend = 22 - 3.75, xend = -69 - 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 0.75, x = -69 + 2,
                     yend = -22 - 3.75, xend = -69 + 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 0.75, x = -69 - 2,
                     yend = -22 - 3.75, xend = -69 - 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 0.75, x = -69 + 2,
                     yend = -22 + 3.75, xend = -69 + 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 0.75, x = -69 - 2,
                     yend = -22 + 3.75, xend = -69 - 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 0.75, x = 69 + 2,
                     yend = -22 + 3.75, xend = 69 + 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 0.75, x = 69 - 2,
                     yend = -22 - 3.75, xend = 69 - 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 + 0.75, x = 69 - 2,
                     yend = -22 + 3.75, xend = 69 - 2), color = "#FFCCD8") +
    ggplot2::geom_segment(aes(y = -22 - 0.75, x = 69 + 2,
                     yend = -22 - 3.75, xend = 69 + 2), color = "#FFCCD8") +
    ggplot2::geom_path(data = data.frame(y = 22 + 15 * cos(theta),
                                x = 69 + 15 * sin(theta)), color = "#FFCCD8") +
    ggplot2::geom_path(data = data.frame(y = 22 + 15 * cos(theta),
                                x = -69 + 15 * sin(theta)), color = "#FFCCD8") +
    ggplot2::geom_path(data = data.frame(y = -22 + 15 * cos(theta),
                                x = -69 + 15 * sin(theta)), color = "#FFCCD8") +
    ggplot2::geom_path(data = data.frame(y = -22 + 15 * cos(theta),
                                x = 69 + 15 * sin(theta)), color = "#FFCCD8") +

    ggplot2::theme_void() +
    ggplot2::coord_fixed()

  return(rink)
}


```



```{r Viz - Histograms of variables}

sd <- df_analysis %>% 
  ggplot(aes(x = ShotDistance, fill = RR)) +
  geom_density(alpha = .5) +
  labs(y = " ") +
  theme_minimal() +
  scale_fill_manual(values = c("#175986","#FFA900"))

pd <- df_analysis %>% 
  ggplot(aes(x = PassDistance, fill = RR)) +
  geom_density(alpha = .5) +
  labs(y = " ") +
  theme_minimal() +
  scale_fill_manual(values = c("#175986","#FFA900"))

sa <-df_analysis %>% 
  ggplot(aes(x = ShotAngle, fill = RR)) +
  geom_density(alpha = .5) +
  labs(y = " ") +
  theme_minimal() +
  scale_fill_manual(values = c("#175986","#FFA900"))

psad <- df_analysis %>% 
  ggplot(aes(x = PassShotAngleDiff, fill = RR)) +
  geom_density(alpha = .5) +
  labs(y = " ") +
  theme_minimal() +
  scale_fill_manual(values = c("#175986","#FFA900"))

comb <-ggarrange(sd, pd, sa, psad, ncol = 4,
                 common.legend = TRUE, legend = "right")

comb


```

```{r Viz - Shot & pass plots}

plotting_data <- df_analysis %>% 
  mutate(pX1 = X.Coordinate - 100,
         pY1 = Y.Coordinate - 42.5,
         pX2 = X.Coordinate.2 - 100,
         pY2 = Y.Coordinate.2 - 42.5)
 

xGshots <- viz_draw_rink() +
  coord_fixed(xlim = c(0, 100)) +
  geom_point(plotting_data, mapping = aes(x = pX2, y = pY2, fill = xG), shape = 23, alpha = .6)

xGpasses <- viz_draw_rink() +
  coord_fixed(xlim = c(0, 100)) +
  geom_point(plotting_data, mapping = aes(x = pX1, y = pY1, fill = xG), shape = 21, alpha = .3) 

xGboth <- viz_draw_rink() +
  coord_fixed(xlim = c(20, 100)) +
  geom_point(plotting_data, mapping = aes(x = pX2, y = pY2, fill = xG), shape = 23, alpha = .8) +
  geom_segment(plotting_data, mapping = aes(x = pX1, y = pY1, xend = pX2, yend = pY2, color = xG), alpha = .25) +
  scale_fill_viridis_c(option = "plasma") +
  scale_color_viridis_c(option = "plasma")


xGboth

```

```{r Viz - Best non-RRPs}

yesRR <- plotting_data %>% 
  filter(RR == TRUE)

nonRR <- plotting_data %>% 
  filter(RR == FALSE)

nonRR90th <- nonRR %>% 
  filter(quantile(xG, .9) < xG)

bestnonRR <- viz_draw_rink() +
  coord_fixed(xlim = c(50, 100)) +
  geom_point(nonRR90th %>% filter(pX1 < 89), 
             mapping = aes(x = pX2, y = pY2), 
             shape = 23, alpha = .8,  color = "#FFA900") +
   geom_point(nonRR90th %>% filter(pX1 >= 89), 
             mapping = aes(x = pX2, y = pY2), 
             shape = 23, alpha = .8, color = "#175986") +
  geom_segment(nonRR90th %>% filter(pX1 < 89),
               mapping = aes(x = pX1, y = pY1, xend = pX2, yend = pY2), alpha = .45, color = "#FFA900") +
  geom_segment(nonRR90th %>% filter(pX1 >= 89),
               mapping = aes(x = pX1, y = pY1, xend = pX2, yend = pY2), alpha = .45, color = "#175986")

bestnonRR


```

```{r Analysis - T-test }

ttest_df <- rbind(nonRR90th, yesRR) %>% 
  select(xG, RR, ShotDistance, ShotAngle)

t.test(xG ~ RR, data = ttest_df)

ancova <- aov(xG ~ RR + ShotDistance + ShotAngle, ttest_df)
Anova(ancova, type=3)

linreg <- lm(xG ~ RR + ShotDistance + ShotAngle, ttest_df)
summary(linreg)

```

